name: Translate

on:
  push:
    branches: [ "*" ]
    paths:
      - src/en-us/**
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip
        pip3 install requests

    - name: Get changed files in src/en-us since last push
      id: get_changes
      run: |
        git fetch origin main
        # Get all changed files in src/en-us since the last push
        CHANGED_FILES=$(git diff --name-only origin/main -- src/en-us/)
        
        # Fix the paths (replace spaces with underscores, for example)
        FIXED_CHANGED_FILES=$(echo "$CHANGED_FILES" | sed 's/ /_/g')
    
        # Output the changed files
        echo "Changed files in src/en-us since last push:"
        echo "$FIXED_CHANGED_FILES"
        
        # Set the fixed changed files as an output variable
        echo "changed_files=$FIXED_CHANGED_FILES" >> $GITHUB_ENV


    - name: Process each changed file
      if: env.changed_files != ''
      run: |
        IFS=$'\n' # Set Internal Field Separator to newline
        for file in ${{ env.changed_files }}; do
          # Replace underscores back to spaces for processing
          original_file="${file//_/ }"
          echo "$file"
          echo "$original_file"
          base_path=$(dirname "$original_file")
          base_name=$(basename "$original_file")
          chinese_file="src/zh-hk/${base_path}/${base_name}"
    
          mkdir -p "src/zh-hk/${base_path}"

